service: webcamapi

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:PutObject"
       Resource:
         Fn::Join:
           - ""
           - - " arn:aws:s3:::face-recognition-models-serverlessapi"
             - Ref: ServerlessDeploymentBucket



functions:

  webcam:
    handler: wsgi_handler.handler
    layers:
      - arn:aws:lambda:us-east-1:939532784043:layer:opencv:1
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: webcam.app
    packRequirements: false
  pythonRequirements:
    noDeploy: 
      - numpy 
      - face_recognition_models

package:
  exclude:
    - venv/**
    - node_modules/**
    - '!node_modules/node-fetch/**'
  include:
    ...